// Build step: embed public assets as base64 TypeScript module
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const PUBLIC = join(import.meta.dir, "..", "public");
const OUT = join(import.meta.dir, "assets.ts");

const mimeMap: Record<string, string> = {
  ".png": "image/png",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".svg": "image/svg+xml",
};

const files = [
  "favicon/avatar-round.png",
  "favicon/avatar-round-32.png",
  "favicon/avatar-round-16.png",
  "favicon/favicon.ico",
  "favicon/favicon-dark-32.svg",
  "favicon/avatar-round.svg",
  "avatar.webp",
];

const entries: string[] = [];
for (const rel of files) {
  const full = join(PUBLIC, rel);
  try {
    const buffer = readFileSync(full);
    const b64 = buffer.toString("base64");
    const ext = "." + (rel.split(".").pop() || "");
    entries.push(`  ${JSON.stringify(rel)}: { mime: ${JSON.stringify(mimeMap[ext] || "application/octet-stream")}, data: ${JSON.stringify(b64)} }`);
  } catch {
    console.warn(`  SKIP ${rel} (not found)`);
  }
}

const out = `// Auto-generated by build-assets.ts
export const assetMap: Record<string, { mime: string; data: string }> = {
${entries.join(",\n")}
};
`;

writeFileSync(OUT, out);
console.log(`Generated ${OUT} with ${entries.length} assets`);
