// Build step: generate a static TypeScript module with all post data
// so Vercel's bundler includes the content in the deployment.
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const POSTS_DIR = join(import.meta.dir, "content", "posts");
const OUT_FILE = join(import.meta.dir, "content", "data.ts");

const files = await readdir(POSTS_DIR);
const posts: { file: string; content: string }[] = [];

for (const f of files) {
  if (!f.endsWith(".md")) continue;
  const content = await readFile(join(POSTS_DIR, f), "utf-8");
  posts.push({ file: f, content });
}

const items = posts
  .map((p) => `  ${JSON.stringify(p.file)}: ${JSON.stringify(p.content)}`)
  .join(",\n");

const out = `// Auto-generated by build-posts.ts — do not edit
export const postsData: Record<string, string> = {
${items}
};
`;

await writeFile(OUT_FILE, out);
console.log(`Generated ${OUT_FILE} with ${posts.length} posts`);
